### ISSUE TITLE
error: No module named '_pytest' after following install instructions

### ISSUE THREAD

**Issue by gavanderhoorn** [colcon/colcon-common-extensions#3] opened 2018-05-03 19:53 UTC
(reporting this here as I installed `colcon-common-extensions`)

`ubuntu:xenial` Docker container. Followed [installation instructions](http://colcon.readthedocs.io/en/latest/user/installation.html) with a `python3` venv.

This installed most of the things I'd expect, but upon first time invoking `colcon --help`, I got:

```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.python_testing.pytest': No module named '_pytest'
Traceback (most recent call last):
  File "/catkin_ws/colcon_venv/lib/python3.5/site-packages/colcon_core/entry_point.py", line 86, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/catkin_ws/colcon_venv/lib/python3.5/site-packages/colcon_core/entry_point.py", line 128, in load_entry_point
    return entry_point.load()
  File "/catkin_ws/colcon_venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/catkin_ws/colcon_venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/catkin_ws/colcon_venv/lib/python3.5/site-packages/colcon_core/task/python/test/pytest.py", line 7, in <module>
    from _pytest.main import EXIT_NOTESTSCOLLECTED
ImportError: No module named '_pytest'

usage: colcon [-h] [--log-level LOG_LEVEL]
              {build,extension-points,extensions,info,list,metadata,test,test-result}
              ...
...
```

After manually installing `pytest` in the virtualenv, this error disappeared.

**Comment by dirk-thomas** [comment] 2018-05-03 20:03
Thanks for the report. The problem has already been addressed in colcon/colcon-core#5 and will be part of the next release.

**Closed as completed** 2018-05-03 20:03 UTC
Labels: bug, duplicate

**Comment by gavanderhoorn** [comment] 2018-05-03 20:05
Is `colcon-core` where all issues should be reported?

**Comment by dirk-thomas** [comment] 2018-05-03 20:09
I would say it depends where the problem is coming from. But if that is unclear `colcon-core` as well as this repo are ok. The ticket can always be moved if necessary.
